#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP response header.
# Install Nginx 
# Configure Nginx to add the custom HTTP header
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
