#!/usr/bin/env bash
# installing a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 54.209.15.61:80 check
    server web-02 54.89.28.234:80 check

"
echo "$server_config" |sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
