#!/usr/bin/env bash
# Stop Nginx
service nginx stop

# Modify the nginx configuration to run as the nginx user and listen on port 8080
sed -i 's/user\s*nginx;/user nginx;\n    listen 8080;/g' /etc/nginx/nginx.conf

# Start Nginx
service nginx start

# Check Nginx status
service nginx status

# Check if Nginx is listening on port 8080
nc -z 0 8080
